working filecheck, spaghetti code

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -12,6 +12,7 @@ AFTER=""
 BEFORE=""
 CURRENCY=""
 filterOUT=""
+#files=()
 SortedCurrArr=()
 SortedCurrAmountArr=()
 
@@ -30,12 +31,41 @@ FILTR může být kombinace následujících:
 exit 0
 }
 
+fileCheck(){
+    if [[ ! -f "$1" ]] ; then
+        exit 1
+    fi
+    readarray -t TradersArr <<<"$(awk -F';' '{print $1}' "$1")"
+    readarray -t DateTimesArr <<<"$(awk -F';' '{print $2}' "$1")"
+    readarray -t CurrenciesArr <<<"$(awk -F';' '{print $3}' "$1")"
+    readarray -t AmountsArr <<<"$(awk -F';' '{print $4}' "$1")"
+    i=0
+    for trader in "${TradersArr[@]}"
+    do
+        if [[ -z "$trader" ]] ; then
+            echo "Invalid log">&2
+            exit 1
+        fi
+        if [[ ! "${DateTimesArr[$i]}" =~ $DATE_TIME_REGEX ]] ; then
+            echo "Invalid date time format in log">&2
+            exit 1
+        fi
+        if [[ -z "${CurrenciesArr[$i]}" ]] ; then
+            echo "Invalid log">&2
+            exit 1
+        fi
+        if [[ -z "${AmountsArr[$i]}" ]] ; then
+            echo "Invalid log">&2
+            exit 1
+        fi
+        
+        i=$((i+1))
+    done
+}
+
 filter(){
     USER=$1
     FILE=$2     #get the user and file from arguments passed to the function
-    if [[ ! -f "$FILE" ]] ; then
-        exit 1
-    fi
     AWKARG="\$1 == user"    #variable to store the eventual argument for awk
     if [[ -n $AFTER ]]; then
         AWKARG+=" && \$2 > after"
@@ -107,7 +137,7 @@ profit(){
     for SortedCurrAmount in "${SortedCurrAmountArr[@]}"
     do
         if awk -v n="$SortedCurrAmount" 'BEGIN { exit !(n > 0) }' ; then    #check if it's bigger than 0, would be nice to use -gt but it doesnt support floating-point numbers
-            SortedCurrAmountArr[$i]=$(awk "BEGIN { printf \"%.4f\", ${SortedCurrAmountArr[$i]} * ($XTF_PROFIT/100+1)}")
+            SortedCurrAmountArr[$i]=$(awk "BEGIN { printf \"%.4f\", ${SortedCurrAmountArr[$i]} * ($XTF_PROFIT/100+1)}") #if it's bigger multiply by (100+XTF_PROFIT)%
         fi
         i=$((i+1))
     done
@@ -121,11 +151,12 @@ printstatus(){
         i=$((i+1))
     done
 }
+
 while getopts ":-:a:b:c:h" opt #a+arg, b+arg, c+arg, h (no arg), -+arg (used for --help)
 do 
     case "$opt" in 
         h)
-            HELP="1"    #tried to do this with OPTIND != 2, but it just refuses to work, idk just kill me
+            HELP="1"
             ;;
         -)  
             case $OPTARG in 
@@ -177,28 +208,35 @@ fi
 
 case "$1" in 
     list)   
+        fileCheck "$3"
         filter "$2" "$3"
         if [[ -n "$filterOUT" ]] ; then
             echo "$filterOUT"
         fi
         ;;
     list-currency)
+        fileCheck "$3"
         getCurrency "$2" "$3"
         if [[ -n "${SortedCurr[*]}" ]] ; then
             echo "${SortedCurr[@]}"              #dont print if no results were found, would result in an empty line
         fi
         ;;
     status)
+        fileCheck "$3"
         status "$2" "$3"
         printstatus
         ;;
     profit)
+        fileCheck "$3"
         profit "$2" "$3"
         printstatus
         ;;
     *)  
+        fileCheck "$2"
         filter "$1" "$2"
-        echo "$filterOUT"
+        if [[ -n "$filterOUT" ]] ; then
+            echo "$filterOUT"
+        fi
         ;;
 esac
 exit 0
