41 tests

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -31,6 +31,26 @@ FILTR může být kombinace následujících:
     exit 0
 }
 
+loadFiles(){
+    start=$1
+    i=$1
+    shift
+    args=("$@")
+    while [ -n "${args[$i]}" ] 
+    do
+        files[$i-$start]="${args[$i]}"
+        i=$((i+1))
+        eval evaled='$'$i
+    done
+    for file in "${files[@]}"
+    do
+        if ! fileCheck "$file" ; then
+            echo "error in file">&2
+            exit 1
+        fi
+    done
+}
+
 fileCheck(){
     if [[ ! -f "$1" ]] ; then
         return 1
@@ -80,8 +100,7 @@ combinedFiles(){
 }
 
 filter(){
-    USER=$1
-    FILE=$2     #get the user and file from arguments passed to the function
+    USER=$1     #get the user from the argument passed to the function
     fileContent=$(combinedFiles)
     if [[ -z "$USER" ]] ; then
         exit 0
@@ -127,7 +146,7 @@ getCurrency(){
 }
 
 status(){
-    getCurrency "$1" "$2" #call filter to get filterOUT based on arguments
+    getCurrency "$1" #call filter to get filterOUT based on arguments
     CurrNames=$(echo "$filterOUT" | awk -F';' '{print $3}')    #save all the currency names left after filtering
     readarray -t CurrNameArr <<<"$CurrNames"    #split results from awk by new line into elements in an array CurrNameArr
     CurrAmounts=$(echo "$filterOUT" | awk -F';' '{print $4}')
@@ -155,7 +174,7 @@ profit(){
     if [[ -z "$XTF_PROFIT" ]] ; then
         XTF_PROFIT=20
     fi
-    status "$1" "$2"
+    status "$1"
     i=0
     for SortedCurrAmount in "${SortedCurrAmountArr[@]}"
     do
@@ -226,21 +245,17 @@ if [ -n "$CURRENCY" ] ;  then
     shift 2
 fi
 
-i=3 #starting at 3 because $1 list/list-currency/status and $2 is user !!! if no command provided file already at $2 MUST CHECK LATER !!
+i=0
 eval evaled='$'$i
 while [ -n "$evaled" ] 
 do
-    files[$i-3]="$evaled"   #-3 so the array starts at zero
+    arguments[$i]="$evaled"
     i=$((i+1))
     eval evaled='$'$i
 done
-for file in "${files[@]}"
-do
-    if ! fileCheck "$file" ; then
-        echo "error in file">&2
-        exit 1
-    fi
-done
+
+loadFiles 3 "${arguments[@]}"
+
 case "$1" in 
     list)
         filter "$2" "${files[@]}"
@@ -263,7 +278,8 @@ case "$1" in
         printstatus
         ;;
     *)  
-        filter "$1" "$2"
+        loadFiles 2 "${arguments[@]}"
+        filter "$1"
         if [[ -n "$filterOUT" ]] ; then
             echo "$filterOUT"
         fi
